"""Fix column

Revision ID: 438d16ec237f
Revises: 7ff77c836fa3
Create Date: 2024-01-25 01:31:50.217645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438d16ec237f'
down_revision = '7ff77c836fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
