"""Fix column donation

Revision ID: 79603fb952a6
Revises: 438d16ec237f
Create Date: 2024-01-25 03:25:18.497706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79603fb952a6'
down_revision = '438d16ec237f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
