"""Add relations

Revision ID: 7ff77c836fa3
Revises: 0467c2ec3ddf
Create Date: 2024-01-24 01:56:29.951037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff77c836fa3'
down_revision = '0467c2ec3ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_donation_charityproject_id_charityproject', 'charityproject', ['charity_project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_charityproject_id_charityproject', type_='foreignkey')
        batch_op.drop_column('charity_project_id')

    # ### end Alembic commands ###
