"""Fix column table

Revision ID: f480f68d518b
Revises: 79603fb952a6
Create Date: 2024-01-28 16:45:00.879306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f480f68d518b'
down_revision = '79603fb952a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_charityproject_id_charityproject', type_='foreignkey')
        batch_op.drop_column('charity_project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_project_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_donation_charityproject_id_charityproject', 'charityproject', ['charity_project_id'], ['id'])

    # ### end Alembic commands ###
